version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PG_HOST: pg
    volumes:
    - ./my-shop:/app
    ports:
      - 3000:5000
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: myuser
      POSTGRES_DB: shop
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata

    ports:
      - 5433:5432
