"""add is_new

Revision ID: 5526a60f19ed
Revises: 6ae67551333f
Create Date: 2020-11-21 20:38:06.652303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5526a60f19ed'
down_revision = '6ae67551333f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
