"""add Deleted

Revision ID: 5b74a8498ddd
Revises: 5526a60f19ed
Create Date: 2020-11-23 00:47:11.202803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b74a8498ddd'
down_revision = '5526a60f19ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted', sa.Boolean(), nullable=False,  server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted')
    # ### end Alembic commands ###
